buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
siteStream:
  id: site-entity
  fields:
    - name
    - c_header
    - c_footer
  localization:
    locales:
      - en
  entityId: "2092081644126552582"
